#2 /korean/outline/intro.md 번역
ClojureBridgeSeoul/curriculum pull request #8
Opened 2017-03-03 07:26 UTC by snowTUBE

2017-03-03 08:23 UTC, snowTUBE commented
#7 sequences.md 번역

2017-03-03 11:32 UTC, snowTUBE commented
#7 sequences.md 함수를 포함하는 함수 --> 함수를 취하는 함수로 수정했습니다.

2017-03-03 12:21 UTC, snowTUBE commented
#5 functions.md 번역

2017-03-06 12:41 UTC, snowTUBE commented
같이 하는 친구와 어투를 맞춰보았습니다.

2017-03-07 12:05 UTC, dalzony requested changes
스윽, 봤어요. 너무 잘해주었습니다. 의미상 문제되는 것은 없어보이고, 말투만 조금 고쳐봤어요. 리뷰 보시고 고쳐주시면 감사하겠습니다.

2017-03-07 12:05 UTC, dalzony commented on outline/functions.md
> +* [보너스 섹션]
섹션이 하나 더 들어간것 같아요. 지워주세요 ;-)

2017-03-07 12:05 UTC, dalzony commented on outline/functions.md
> +* [보너스 섹션] 할당하기: `let`
해석상으로는 할당이 맞지만, 클로저에서 쓰임상 다음과 같이 해석하면 좋을거 같아요.

```
`let`으로 로컬 바인딩하기 
```

2017-03-07 12:05 UTC, dalzony commented on outline/functions.md
> +> `count`, `conj`, `first`, 그턴고  `rest` 같은 몇 가지 함수들을 본 적이 있습니다.
이렇게 고치면 어떨까요?
`count`, `conj`, `first`, `rest` 같은 함수들을 살펴봤습니다.

2017-03-07 12:05 UTC, dalzony commented on outline/functions.md
> +> 우리가 사용한 모든 산술 연산도 마찬가지로 함수입니다 : `+`, `-`, `*`, `/`
마찬가지로, 우리가 사용한 모든 산술 연산도 함수 입니다. : `+`, `-`, `*`, `/`

2017-03-07 12:05 UTC, dalzony commented on outline/functions.md
> +> 우리가 사용한 모든 산술 연산도 마찬가지로 함수입니다 : `+`, `-`, `*`, `/`
이렇게? ㅋ

2017-03-07 12:05 UTC, dalzony commented on outline/functions.md
> +> *함수*란 독립적이고 개별적인 코드로, (*인자*라고 하는) 값을 취하고 값을 반환합니다.
`취하고` 대신에 `받고` 면 될 것 같습니다.

2017-03-07 12:05 UTC, dalzony commented on outline/functions.md
> +* 값을 취하고 값을 반환하는 코드
값을 받고 값을 반환하는 코드

2017-03-07 12:05 UTC, dalzony commented on outline/functions.md
> +> 함수를 인자로 취하는 또 다른 함수를 살펴봅시다.
취하는 -> 받는

2017-03-07 12:05 UTC, dalzony commented on outline/functions.md
> +> `reduce`함수는 제공된 컬렉션의 처음 두 멤버를 취하고 그 멤버들에게 제공된 함수를 호출합니다.
취하고 -> 받고

2017-03-07 12:05 UTC, dalzony commented on outline/sequences.md
> +> `dotimes`는 `[name의 최대정수]`를 인자로 취합니다.
취합니다 -> 받습니다

2017-03-07 12:16 UTC, snowTUBE commented
취하다 -> 받다
그 외 부분 수정했습니다.

2017-03-07 12:21 UTC, dalzony commented
👍 @snowTUBE 고생하셨습니다~!

2017-03-07 12:22 UTC, merged