#3 simple_values.md 번역
ClojureBridgeSeoul/curriculum pull request #9
Opened 2017-03-03 08:03 UTC by 11mia

2017-03-03 09:28 UTC, 11mia commented
#6 flow_control.md 번역입니다!

2017-03-03 11:13 UTC, 11mia commented
#4 data_structures.md 번역입니다!

2017-03-06 12:50 UTC, 11mia commented
말투맞춰서 다시 수정했습니다!

2017-03-07 12:20 UTC, dalzony requested changes
바꾸면 좋겟다고 생각한 것에 댓글 남겼어요~! 고쳐서 커밋 부탁드릴게요.

2017-03-07 12:20 UTC, dalzony commented on outline/data_structures.md
> +> 지금까지, 데이터 하나하나를 다뤘습니다:숫자,문자열,값.  프로그래밍시에는 데이터들의 묶음을 가지고 작업하는 경우가 더 많습니다.
데이터들의 묶음, 즉 `콜렉션`을 가지고 작업하는 경우가 더 많습니다.

로 수정하면 좋을 것 같습니다.

2017-03-07 12:20 UTC, dalzony commented on outline/data_structures.md
> +#### 순차적인 모음 <button class="link" ng-bind-html="details" ng-model="block21" ng-click="block21=!block21"></button>
순서가 있는 콜렉션

정도로 바꾸면 될것 같습니다.

2017-03-07 12:20 UTC, dalzony commented on outline/data_structures.md
> +> 벡터는 값들의 순차적인 모음입니다. 벡터는 비어있을 수 있습니다. 벡터는 다른 타입의 값들을 담을 수 있습니다. 벡터의 값들은 0에서부터 시작하고 이 숫자를 인덱스라고 합니다. 인덱스는 값들을 참조할 때 사용합니다.
벡터는 값들의 순차적인 모음입니다.-> 벡터는 순서가 있는 값들의 모음입니다.

2017-03-07 12:20 UTC, dalzony commented on outline/data_structures.md
> +> 벡터는 값들의 순차적인 모음입니다. 벡터는 비어있을 수 있습니다. 벡터는 다른 타입의 값들을 담을 수 있습니다. 벡터의 값들은 0에서부터 시작하고 이 숫자를 인덱스라고 합니다. 인덱스는 값들을 참조할 때 사용합니다.
벡터는 비어있을 수 있습니다. 벡터는 다른 타입의 값들을 담을 수 있습니다.
-> 벡터는 비어 있을 수 있으며, 서롤 다른 타입의 값들도 담을 수 있습니다.

2017-03-07 12:20 UTC, dalzony commented on outline/data_structures.md
> +> 벡터는 값들의 순차적인 모음입니다. 벡터는 비어있을 수 있습니다. 벡터는 다른 타입의 값들을 담을 수 있습니다. 벡터의 값들은 0에서부터 시작하고 이 숫자를 인덱스라고 합니다. 인덱스는 값들을 참조할 때 사용합니다.
벡터의 값들은 0에서부터 시작하고 이 숫자를 인덱스라고 합니다.
->
벡터의 값들은 순서를 매길때 에 0부터 세고, 이 숫자를 인덱스라고 합니다.

2017-03-07 12:20 UTC, dalzony commented on outline/data_structures.md
> +> 그 숫자는 0부터 시작되한다는 것을 주의하세요. 이상하게 보일 수도 있지만 프로그래밍시에는 0부터 계산해야 합니다.
프로그래밍시에는 -> 프로그래밍 할 때는

2017-03-07 12:20 UTC, dalzony commented on outline/data_structures.md
> +> 맵을 생성한 후 키에 새로운 값을 연결시키기를 원할 수 있습니다. `assoc`함수는 기존의 키에 새로운 값을 추가할 때 사용될 수 있습니다. 또, `update`라는 편리한 함수도 있습니다. `update`는 맵과 키를 함께 사용합니다. 특정한 키는 함수의 첫번째 인자가 됩니다. `update-in`함수는 `update`처럼 작동하지만 중첩된 맵의
`>` 이런 형식도 모두 마크다운 문법이라 맞추어 줘야 할 것 같습니다.

2017-03-07 12:20 UTC, dalzony commented on outline/data_structures.md
> +> 수,키워드,문자열과 같은 값들만이 collection에 넣을 수 있는 것은 아닙니다. 다른 collections들도 collection에 넣을 수 있으므로 맵의 벡터, 벡터의 리스트와 같이 데이터에 맞는 조합을 가질 수 있습니다.
여기도 
`>` 이런 형식도 모두 마크다운 문법이라 맞추어 줘야 할 것 같습니다.

2017-03-07 12:20 UTC, dalzony commented on outline/data_structures.md
> +> 수,키워드,문자열과 같은 값들만이 collection에 넣을 수 있는 것은 아닙니다. 다른 collections들도 collection에 넣을 수 있으므로 맵의 벡터, 벡터의 리스트와 같이 데이터에 맞는 조합을 가질 수 있습니다.
여기서 collection or collections 는 모두 `콜렉션` 한국말로 적어도 될것 같아요.

2017-03-07 12:20 UTC, dalzony commented on outline/flow_control.md
> -Flow Control
flow control은 모두, `흐름제어` 보다는  '조건문'으로 바꾸면 될 것 같습니다.

2017-03-07 12:20 UTC, dalzony commented on outline/flow_control.md
> +> 클로저에서 흐름제어를 하기 위한 가장 기본적인 방법이 `if`연산자입니다.
클로저에서 조건문을 쓸때, 가장 기본적으로 `if`연산자를 사용합니다.

2017-03-07 12:20 UTC, dalzony commented on outline/simple_values.md
> +> 마지막으로 ratio라고도 불리는 분수가 있습니다. 컴퓨터는 모든 소수를 완벽하
마지막으로 ratio라고도 불리는 분수 데이터 형식이 있습니다.

2017-03-07 12:38 UTC, 11mia commented
수정했습니다!

2017-03-07 12:41 UTC, merged